import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Our first Next.js application</h1>
        <Link href="/">Home</Link>
        <Link href="/todos">Todos</Link>
        <Link href="/profile">Profile</Link>
        {children}
      </body>
    </html>
  );
}
